#!/usr/bin/env bash
# shellcheck disable=SC2034
# Minimal implementation of Bashio constants for docker-pluggie

# Default supervisor API details
declare __BASHIO_DEFAULT_SUPERVISOR_API="http://supervisor/core/api"
declare __BASHIO_DEFAULT_SUPERVISOR_TOKEN=""

# Log level
declare __BASHIO_LOG_LEVEL_ALL=8
declare __BASHIO_LOG_LEVEL_TRACE=7
declare __BASHIO_LOG_LEVEL_DEBUG=6
declare __BASHIO_LOG_LEVEL_INFO=5
declare __BASHIO_LOG_LEVEL_NOTICE=4
declare __BASHIO_LOG_LEVEL_WARNING=3
declare __BASHIO_LOG_LEVEL_ERROR=2
declare __BASHIO_LOG_LEVEL_FATAL=1
declare __BASHIO_LOG_LEVEL_CRITICAL=1
declare __BASHIO_LOG_LEVEL_OFF=0

# Default log settings
declare __BASHIO_DEFAULT_LOG_LEVEL=${__BASHIO_LOG_LEVEL_INFO}
declare __BASHIO_DEFAULT_LOG_FORMAT="%b"
declare __BASHIO_DEFAULT_LOG_TIMESTAMP="%T"

# Colors
__BASHIO_COLORS_ESCAPE="\033[";
__BASHIO_COLORS_RESET="${__BASHIO_COLORS_ESCAPE}0m"
__BASHIO_COLORS_DEFAULT="${__BASHIO_COLORS_ESCAPE}39m"
__BASHIO_COLORS_BLACK="${__BASHIO_COLORS_ESCAPE}30m"
__BASHIO_COLORS_RED="${__BASHIO_COLORS_ESCAPE}31m"
__BASHIO_COLORS_GREEN="${__BASHIO_COLORS_ESCAPE}32m"
__BASHIO_COLORS_YELLOW="${__BASHIO_COLORS_ESCAPE}33m"
__BASHIO_COLORS_BLUE="${__BASHIO_COLORS_ESCAPE}34m"
__BASHIO_COLORS_MAGENTA="${__BASHIO_COLORS_ESCAPE}35m"
__BASHIO_COLORS_CYAN="${__BASHIO_COLORS_ESCAPE}36m"
__BASHIO_COLORS_LIGHT_GRAY="${__BASHIO_COLORS_ESCAPE}37m"
__BASHIO_COLORS_BG_DEFAULT="${__BASHIO_COLORS_ESCAPE}49m"
__BASHIO_COLORS_BG_BLACK="${__BASHIO_COLORS_ESCAPE}40m"
__BASHIO_COLORS_BG_RED="${__BASHIO_COLORS_ESCAPE}41m"
__BASHIO_COLORS_BG_GREEN="${__BASHIO_COLORS_ESCAPE}42m"
__BASHIO_COLORS_BG_YELLOW="${__BASHIO_COLORS_ESCAPE}43m"
__BASHIO_COLORS_BG_BLUE="${__BASHIO_COLORS_ESCAPE}44m"
__BASHIO_COLORS_BG_MAGENTA="${__BASHIO_COLORS_ESCAPE}45m"
__BASHIO_COLORS_BG_CYAN="${__BASHIO_COLORS_ESCAPE}46m"
__BASHIO_COLORS_BG_WHITE="${__BASHIO_COLORS_ESCAPE}47m"

# Default cache directory
declare __BASHIO_DEFAULT_CACHE_DIR="/tmp/.bashio"