name: Pluggie
version: 0.3.8
slug: pluggie
description: Make your device visible! (Pluggie)
url: https://pluggie.net
codenotary: egresh@pluggie.net
image: ghcr.io/tiborgres/ha-pluggie
arch:
- aarch64
- amd64
- armhf
- armv7
- i386
apparmor: true
host_network: false
host_ipc: false
host_dbus: false
host_pid: false
host_uts: false
init: false
hassio_api: false
homeassistant_api: false
auth_api: false
full_access: false
ingress: true
audio: false
video: false
gpio: false
usb: false
uart: false
devicetree: false
tmpfs: false
stdin: false
legacy: false
privileged:
- NET_ADMIN
devices:
- /dev/net/tun
map:
- ssl:rw
panel_icon: mdi:connection
options:
  message: Enable the sidebar icon and click on Pluggie to access all addon settings.
    Nothing to configure here.
schema:
  message: str
